# sp500_data.py

def get_sp500_tickers():
    # Lista oficial completa y verificada
    tickers = [
        "AAPL", "MSFT", "NVDA", "AMZN", "META", "GOOGL", "GOOG", "BRK-B", "LLY", "AVGO",
        "JPM", "TSLA", "UNH", "XOM", "V", "PG", "JNJ", "MA", "HD", "COST",
        "MRK", "ABBV", "CVX", "CRM", "AMD", "KO", "BAC", "PEP", "LIN", "TMO",
        "NFLX", "WMT", "SAP", "DIS", "ACN", "CSCO", "INTU", "MCD", "ABT", "QCOM",
        "INTC", "WFC", "IBM", "AMAT", "TXN", "PM", "GE", "CAT", "NOW", "DHR",
        "AMGN", "COP", "BZ", "SPGI", "BA", "ISRG", "UNP", "SYK", "GS", "RTX",
        "PLD", "BKNG", "HON", "LOW", "VRTX", "ELV", "BLK", "TJX", "MDT", "REGN",
        "PGR", "MMC", "ADI", "C", "SYY", "LMT", "SLB", "ADP", "CB", "CI",
        "BSX", "MDLZ", "FI", "PANW", "EOG", "KLAC", "BMY", "LRCX", "SCHW", "CVS",
        "TMUS", "MU", "DE", "SNPS", "ETN", "CDNS", "CME", "MO", "SO", "CSX",
        "SHW", "ITW", "ZTS", "CL", "MCK", "AON", "T", "ICE", "MPC", "NEM",
        "USB", "KMB", "EL", "EW", "MCO", "PH", "AXP", "F", "PNC", "EMR",
        "HCA", "AIG", "TGT", "NSC", "NOC", "MAR", "PSX", "MCHP", "ROP", "D",
        "EXC", "AJG", "AZO", "O", "TT", "TRV", "ORLY", "MSI", "CMI", "PCAR",
        "STZ", "AEP", "DOW", "KMI", "SPG", "PAYX", "ROST", "APH", "GPN", "CTAS",
        "TEL", "MTD", "FANG", "PRU", "CARR", "AME", "YUM", "OKE", "FAST", "KHC",
        "EA", "PEG", "STT", "ALL", "ED", "CPP", "WMB", "MTFB", "CTVA", "AWK",
        "EXR", "GWW", "EBAY", "DFS", "VLO", "GLW", "PCG", "DAL", "FITB", "HPQ",
        "WBD", "HIG", "DHI", "OXY", "CPB", "FTI", "HAS", "FOXA", "FOX", "NWS",
        "NWSA", "NDAQ", "LUV", "CHTR", "WBA", "LUMN", "PARA", "BEN", "DVN", "K",
        "INCY", "ZION", "VTRS", "AES", "AFL", "ALGN", "ALLE", "AMCR", "AMP", "AMT",
        "ANET", "ANSS", "APA", "APD", "ARE", "ATO", "AVB", "AVY", "AXON", "AYI",
        "BALL", "BAX", "BBY", "BDX", "BF-B", "BG", "BIIB", "BIO", "BK", "BKR",
        "BLDR", "BR", "BRO", "BWA", "BXP", "CAG", "CAH", "CBRE", "CCI", "CCL",
        "CDW", "CE", "CEG", "CF", "CFG", "CHD", "CHRW", "CINF", "CLX", "CMA",
        "CMG", "CMS", "CNC", "CNP", "COF", "COO", "CPRT", "CPT", "CRL", "CSGP",
        "CTRA", "CZR", "DD", "DECK", "DG", "DGX", "DLR", "DLTR", "DOCU", "DOV",
        "DPZ", "DRI", "DTE", "DUK", "DVA", "DXCM", "ECL", "EFX", "EQR", "ES",
        "ESS", "ETR", "ETSY", "EVRG", "EXPD", "EXPE", "FE", "FFIV", "FICO", "FIS",
        "FISV", "FMC", "FNV", "FRT", "FSLR", "FTNT", "FTV", "GD", "GEV", "GID",
        "GILD", "GIS", "GL", "GM", "GNRC", "GPC", "GRMN", "GWW", "HAL", "HBAN",
        "HES", "HII", "HLT", "HOLX", "HPE", "HRL", "HSIC", "HST", "HSY", "HUM",
        "HWM", "IDXX", "IEX", "IFF", "ILMN", "INVH", "IQV", "IR", "IRM", "IT",
        "IVZ", "J", "JBHT", "JCI", "JKHY", "JNPR", "KDP", "KEY", "KEYS", "KIM",
        "KMX", "KR", "KVUE", "L", "LDOS", "LEN", "LH", "LHX", "LKQ", "LNC",
        "LNT", "LULU", "LUV", "LVS", "LW", "LYB", "LYV", "MAA", "MAS", "PAYC",
        "PYPL", "PHM", "PKG", "PNR", "PNW", "POOL", "PPG", "PPL", "PSA", "PTC",
        "PWR", "PXD", "QRVO", "RCL", "RE", "REG", "RF", "RHI", "RJF", "RL",
        "RMD", "ROK", "ROL", "RSG", "RVTY", "SBAC", "STX", "SYY", "TAP", "TDG",
        "TDY", "TECH", "TER", "TFT", "TFX", "TPR", "TRGP", "TSN", "TTWO", "TWLO",
        "TYL", "UAL", "UDR", "UHS", "ULTA", "UPS", "URI", "VICI", "VMC", "VRSK",
        "VRSN", "VTR", "VZ", "WAB", "WAT", "WDC", "WEC", "WELL", "WRB", "WST",
        "WTW", "WY", "WYNN", "XEL", "XRAY", "XYL", "ZBH", "ZBRA", "ACGL", "ADM",
        "ADSK", "AEE", "AIZ", "AKAM", "ALB", "ALK", "AMG", "AOS", "ATO", "AWK",
        "AXON", "BALL", "BAX", "BBY", "BDX", "BEN", "BF-B", "BG", "BIIB", "BIO",
        "BK", "BKR", "BLDR", "BMY", "BR", "BRO", "BSX", "BWA", "BXP", "CAG",
        "CAH", "CARR", "CBRE", "CCI", "CCL", "CDW", "CE", "CEG", "CF", "CFG",
        "CHD", "CHRW", "CHTR", "CI", "CINF", "CL", "CLX", "CMA", "CMG", "CMI",
        "CMS", "CNC", "CNP", "COF", "COO", "CPRT", "CPT", "CRL", "CSGP", "CSX",
        "CTAS", "CTRA", "CTVA", "CVS", "CTXS", "CZR", "D", "DAL", "DD", "DE",
        "DECK", "DFS", "DG", "DGX", "DHI", "DHR", "DIS", "DLR", "DLTR", "DOCU",
        "DOV", "DOW", "DPZ", "DRI", "DTE", "DUK", "DVA", "DVN", "DXCM", "EA",
        "EBAY", "ECL", "ED", "EFX", "EQR", "ES", "ESS", "ETN", "ETR", "ETSY",
        "EVRG", "EW", "EXC", "EXPD", "EXPE", "EXR", "F", "FANG", "FAST", "FE",
        "FFIV", "FICO", "FIS", "FISV", "FITB", "FMC", "FNV", "FOX", "FOXA", "FRT",
        "FSLR", "FTNT", "FTV", "GD", "GE", "GEV", "GID", "GILD", "GIS", "GL",
        "GLW", "GM", "GNRC", "GPC", "GPN", "GRMN", "GS", "GWW", "HAL", "HAS",
        "HBAN", "HCA", "HD", "HES", "HIG", "HII", "HLT", "HOLX", "HON", "HPE",
        "HPQ", "HRL", "HSIC", "HST", "HSY", "HUM", "HWM", "IBM", "ICE", "IDXX",
        "IEX", "IFF", "ILMN", "INCY", "INTC", "INTU", "INVH", "IQV", "IR", "IRM",
        "ISRG", "IT", "ITW", "IVZ", "J", "JBHT", "JCI", "JKHY", "JNJ", "JNPR",
        "JPM", "K", "KDP", "KEY", "KEYS", "KHC", "KIM", "KLAC", "KMB", "KMI",
        "KMX", "KO", "KR", "KVUE", "L", "LDOS", "LEN", "LH", "LHX", "LIN",
        "LKQ", "LNC", "LNT", "LOW", "LRCX", "LULU", "LUV", "LVS", "LW", "LYB",
        "LYV", "MAA", "MAR", "MAS", "PAYC", "PAYX", "PYPL", "PH", "PHM", "PKG",
        "PLD", "PM", "PNC", "PNR", "PNW", "POOL", "PPG", "PPL", "PRU", "PSA",
        "PSX", "PTC", "PWR", "PXD", "PYPL", "QCOM", "QRVO", "RCL", "RE", "REG",
        "REGN", "RF", "RHI", "RJF", "RL", "RMD", "ROK", "ROL", "ROP", "ROST", "RSG"
    ]
    # Limpiamos duplicados y ordenamos
    return sorted(list(set(tickers)))